- hosts: all
  tasks:
    - name: change a str
      lineinfile: dest=/home/user/.config/lxpanel/LXDE/panels/panel
                  regexp='id=firefox.desktop'
                  insertbefore=BOF
                  line='id=firefox.desktop-esr'  
