- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: file/firefox.desktop
      dest: /home/user/Рабочий\ стол 
      owner: user
      group: user
      mode: 0644
      force: yes
