- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: file/x11vnc.service
      dest: /lib/systemd/system/x11vnc.service 
#      owner: chgb_user
#      group: root
      mode: 0644
      force: yes
