- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: /etc/skel/.config/
      dest: /home/user/.config/
      owner: user
      group: users
      mode: 0644
      directory_mode: yes
      force: yes
      
- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: /etc/skel/.local/
      dest: /home/user/.local/
      owner: user
      group: users
      mode: 0644
      directory_mode: yes
      force: yes
