- hosts: all
  tasks:

   - name: copy file force                                #stop vipnetclient
     copy:
       src: file/ECP.desktop
       dest: "{{ item }}"
       mode: 0777
       force: yes
     with_items:
        - /home/user/Рабочий стол/ECP.deskto"
        - /home/user/Desktop/ECP.deskto"
