- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: file/firefox.desktop
      dest: /home/user/Рабочий стол/firefox.desktop 
      owner: user
      group: users
      mode: 0644
      force: yes
