- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: file/org.opensuse.cupspkhelper.mechanism.policy
      dest: /usr/share/polkit-1/actions/org.opensuse.cupspkhelper.mechanism.policy
 #     owner: user
#      group: user
 #     mode: 0644
      force: yes
