- hosts: all
  tasks:
  - name: Ansible copy org.opensuse.cupspkhelper.mechanism.policy
    copy:
      src: file/org.opensuse.cupspkhelper.mechanism.policy
      dest: /usr/share/polkit-1/actions/org.opensuse.cupspkhelper.mechanism.policy
 #     owner: user
#      group: user
 #     mode: 0644
      force: yes

- hosts: all
  tasks:
  - name: Ansible copy system-config-printer.desktop
    copy:
      src: file/system-config-printer.desktop
      dest: /home/user/Рабочий стол/system-config-printer.desktop
      owner: user
      group: user
      mode: 0744
      force: yes
      
- hosts: all
  tasks:
  - name: Ansible copy peazip.desktop
    copy:
      src: /etc/skel/.local/share/applications/peazip.desktop
      dest: /home/user/.local/share/applications/peazip.desktop 
      owner: user
      group: users
      mode: 0744
      remote_src: yes
      force: yes
