- hosts: all
  gather_facts: no
  tasks:

  - stat: test path
    path: path=/home/user/Рабочий стол/
    register: st
    failed_when: st.stat.exists

  - name: copy file force                               
    copy:
      src: file/ECP.desktop
      dest: /home/user/Рабочий стол/ECP.desktop
      mode: 0777
      force: yes
     when: fistle.stat.exists

  - stat: test path
    path: path=/home/user/Desktop/
    register: st
    failed_when: st.stat.exists

  - name: copy file force                              
    copy:
      src: file/ECP.desktop
      dest: /home/user/Desktop/ECP.desktop
      mode: 0777
      force: yes
     when: fistle.stat.exists
