- hosts: all
  tasks:
  - name: Ansible copy file force
    copy:
      src: file/ECP.desktop
      dest: /home/user/Рабочий стол/ECP.desktop
#      owner: chgb_user
#      group: root
      mode: 0777
      force: yes
