- hosts: all
  tasks:
  - name: Disable cups.service
    gather_facts: no
    systemd:
      name: cups.service
#      state: started
      enabled: no
     
- hosts: all
  tasks:
  - name: Enable cups.service
    gather_facts: no
    systemd:
      name: cups.socket
      enabled: yes 
