- hosts: all
  tasks:
   - name: Clean opt_firefox
     file:
       state: absent
       path: "{{ /opt/firefox }}/"
      
  tasks:
   - name: Clean  shortcut firefox
     file:
       state: absent
       path: "{{ /usr/share/applications/firefox.desktop }}/"
