- hosts: all
  gather_facts: no
  #команды
  tasks:
    - shell: hostname; apt purge secretnet -y; cat /proc/cpuinfo|grep "model name"
      register: hostname

    # Print the shell task's stdout.
    - debug: msg={{ hostname.stdout }}
