- hosts: all      
  tasks:
   - name: Clean  shortcut firefox
     file:
       path: "{{ item }}"
       state: absent
     with_items:
       - /root/.ssh/ansible
       - /root/.ssh/ansible.pub        
