- hosts: all
  gather_facts: no
  tasks:
    - name: Create multiple text file in tmp directory with shell module
        shell: |
          echo vipnetclient info|grep "Host name"   >> file/host
          echo "This will go in memory file">> file/host
