- hosts: all
  gather_facts: no
  tasks:
    - shell: hostname; vipnetclient info|grep "Host name"
      register: hostname

    # Print the shell task's stdout.
    - debug: msg={{ hostname.stdout }}
