- hosts: all
  gather_facts: no
  tasks:
    - name: Create multiple text file in tmp directory with shell module
      shell: "{{ item }}"
      with_items:
         - hostname  > file/host
         - vipnetclient info|grep "Host name"  > file/host
         - echo "-----------------------------------------"  > file/host
