- hosts: all
  gather_facts: no
  tasks:
    - name: Create multiple text file in tmp directory with shell module
      shell: "{{ item }}"
      with_items:
         - hostname
         - vipnetclient info|grep "Host name"
         - echo "-----------------------------------------"
