- hosts: all
  gather_facts: no
  tasks:
    - shell: hostname; vipnetclient info|grep "Host name"; cat /proc/cpuinfo|grep "model name"
      register: hostname

    # Print the shell task's stdout.
    - debug: msg={{ hostname.stdout }}
