- hosts: all
  
  tasks:
    - name: Update apt cache
      apt: update_cache=no
      
    - name: Install required packages
      apt: name={{ item }}      
      with_items:
        - firefox-esr
        - firefox-esr-l10n-ru
