# НЕОБХОДИМО ПОСТАВИТЬ НУЖНУЮ ВЕРСИЮ SECRET NET
- hosts: all
  gather_facts: no
  
  vars:
    grub_selections: |
      grub-pc grub-pc/install_devices select
      grub-pc grub-pc/install_devices_multiselect select
  
  tasks:
    - name: "Скачивание архива с удаленного доступа"
      shell: |
         cd /opt
         wget --user={{ usr }} --password={{ passw }} ftp://192.168.100.22/SN_LSP.tar 
    - name: "Разархивация SN_LSP.tar"
      unarchive:
         remote_src: true  # Искать файл на удаленном узле
         src: /opt/SN_LSP.tar  # Путь к файлу архива
         dest: /opt/  # Путь к каталогу, куда нужно разархивировать       
    - name: "Удаление файла SN_LSP.tar"
      file:
        path: /opt/SN_LSP.tar
        state: absent
    - name: "Разархивация"
      shell: |
         cd /opt/SN_LSP/
         tar -xf debian10.1.tar.gz     
    - name: "Выполнение файла edit_repo.py"
      shell: |
         python3 edit_repo.py /opt/SN_LSP/repo
         truncate -s 0 /etc/apt/sources.list
    
    - name: "Меняем значение sources.list"
      shell: |
         echo "deb [trusted=yes] file:///opt/SN_LSP/repo ./" | sudo tee -a /etc/apt/sources.list
         apt update  
         
    - name: Установка пакета grub-pc
      apt:
        name: grub-pc
        state: present
      register: grub_install_result

    - name: Ответ на настройку grub-pc
      debconf:
        name: "{{ item.split()[0] }}"
        question: "{{ item.split()[1] }}"
        value: "{{ item.split()[2] }}"
      with_items: "{{ grub_selections.split('\n') }}"
      when: grub_install_result is success

    - name: Обновление grub
      command: update-grub
    
    - name: "1. Установка SecretNeta"
      shell: |
         cd /opt/SN_LSP/
         apt install ./sn-lsp_1.10-660.debian10.1_amd64.deb -y
         



      
  
    - name: "Reboot пк"
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
      
    - name: "Происходит перезапуск системы, осталось немного"
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
      become: false
      delegate_to: localhost
