- hosts: all
  gather_facts: no
  tasks:
    - name: "Меняем sources.list на правильный из GitHub"  
      become: yes
      copy:
        src: file/sources2.list
        dest: /etc/apt/sources.list
        force: yes        
  
    - name: "Копия fstab" 
      shell: |
         cp /etc/fstab /etc/fstab.backup 

    - name: "<apt update>"
      ignore_errors: yes
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: "Репы для Yandex и Установка пакета apt-transport-https" 
      shell: |
         wget https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG -O- | sudo apt-key add -
         apt install apt-transport-https -y

    - name: "Выполнение команды 1. <apt update>"
      apt:
        update_cache: yes
        force_apt_get: yes
        
    - name: "Установка python-apt"
      apt:
        name: python-apt
        state: present
      become: true
      become_user: root
      ignore_errors: yes
        
    # Удаляем SecretNet через apt
    - name: "Удаление программы SecretNet"
      apt:
        name: secretnet
        state: absent
        
    - name: "Возвращаем fstab из backup после удаления SecretNet"
      shell: |
         cp /etc/fstab.backup /etc/fstab

    - name: "Выполнение команды 1. <apt update>"
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: "Установка пакетов для следующих команд"
      ignore_errors: yes
      shell: |
         apt-get install gnustep-base-runtime libgnustep-base1.26 -y
        

    - name: "Выполнение команды 2. <apt upgrade>"
      apt:
        upgrade: yes
        force_apt_get: yes
      ignore_errors: yes
        
    - name: "Выполнение команды 3. <apt dist-upgrade>"
      apt:
        upgrade: dist
        force_apt_get: yes
      ignore_errors: yes
        
# ОБНОВЛЕНИЕ ЯДРА!
    - name: "Выполнение команды 1. <apt update>"
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: "Установка ядра linux-image-4.19.0-6-amd64"
      apt:
        name: linux-image-4.19.0-6-amd64
        state: present
        update_cache: yes
        force_apt_get: yes
      ignore_errors: yes
      become: true
      become_user: root

    - name: "Меняем GRUB на правильный"
      shell: |
         sed -i '/^GRUB_DEFAULT=/d' /etc/default/grub
         sed -i '1s/.*/GRUB_DEFAULT="Debian GNU\/Linux, with Linux 4.19.0-6-amd64"/' /etc/default/grub

    - name: "Update-grub"
      shell: |
         update-grub
      ignore_errors: yes

    - name: "Заморозка ядра"
      shell: |
         apt-mark hold linux-image-4.19.0-6-amd64

# Вторая часть называется Part_two.yml
# Установка ПК
    - name: "Скачивание архива с удаленного доступа"
      shell: |
         cd /opt
         wget --user={{ usr }} --password={{ passw }} ftp://192.168.100.22/SN_LSP.tar 
    - name: "Разархивация SN_LSP.tar"
      unarchive:
         remote_src: true  # Искать файл на удаленном узле
         src: /opt/SN_LSP.tar  # Путь к файлу архива
         dest: /opt/  # Путь к каталогу, куда нужно разархивировать       
    - name: "Удаление файла SN_LSP.tar"
      file:
        path: /opt/SN_LSP.tar
        state: absent
    - name: "Разархивация"
      shell: |
         cd /opt/SN_LSP/
         tar -xf debian10.1.tar.gz     
    - name: "Выполнение файла edit_repo.py"
      shell: |
         python3 edit_repo.py /opt/SN_LSP/repo
         truncate -s 0 /etc/apt/sources.list
    - name: "Меняем значение sources.list"
      shell: |
         echo "deb [trusted=yes] file:///opt/SN_LSP/repo ./" | sudo tee -a /etc/apt/sources.list
         apt update  
  
    - name: "Reboot пк"
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
