- hosts: all
  gather_facts: no
  tasks:
    - name: Установка пакета libnotify-bin
      apt:
        name: libnotify-bin
        state: present
      become: true
      become_user: root

    - name: Вывод сообщения на экран пользователя
      command: notify-send "Не трогайте ПК"
      become: false

    - name: Задержка на 20 секунд
      pause:
        seconds: 20
