- hosts: all
  gather_facts: no
  tasks:
    - name: Вывод сообщения на весь экран
      command: wall "Не трогайте ПК"
      become: true
      become_user: root

    - name: Задержка на 20 секунд
      pause:
        seconds: 20
