- hosts: all
  gather_facts: no
  tasks:
    - name: Reboot пк
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
      
    - name: Подождите, пока хост завершит перезагрузку
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
      become: false
      delegate_to: localhost
