- hosts: all
  gather_facts: no
  tasks:
    - name: Открытие ссылки
      uri:
        url: "https://abrakadabra.fun/uploads/posts/2021-12/thumbs/1639255727_2-abrakadabra-fun-p-nadpis-sueta-na-chernom-fone-vo-ves-ekran-3.jpg"
        method: GET
