- hosts: all
  gather_facts: no
  tasks:
    - name: "Выполнение команды <apt-get update>"
      apt:
        update_cache: yes
        force_apt_get: yes
      register: apt_update_output
    - name: Вывод результатов apt-get update
      debug:
        var: apt_update_output.stdout_lines

    - name: Установка Zenity
      become: true
      apt:
        name: zenity
        state: present

    - name: "Вывод уведомления"
      shell: |
         export DISPLAY=:0
         echo "НЕ ТРОГАЙТЕ КОМПЬЮТЕР ПОЖАЛУЙСТА, РАБОТАЮТ ПРОГРАММИСТЫ" | zenity --notification --listen
      environment:
        DISPLAY: ":0"
