- hosts: all
  gather_facts: no
  tasks:
    - name: "Reboot системы"
      shell: |
        reboot
      register: reboot
    - name: Вывод результатов Reboot системы
      debug:
        var: reboot.stdout_lines

    - name: "Ожидание доступности системы"
      wait_for_connection:
        delay: 30
        timeout: 300
      become: false

    - name: "Вывод сообщения после перезагрузки"
      debug:
        msg: "Система ребутнулась и подключилась для дальнейшей работы"
