- hosts: all
  tasks:
    - name: Find_str_to_file
      shell: cat /home/user/.config/mimeapps.list | grep x-scheme-handler/smb=pcmanfm.desktop | wc -l
      register: StrFind
    - debug: msg="{{StrFind.stdout}}"
