- hosts: all
  gather_facts: no
  tasks:
  - name: Copy sert
    copy:
      src: file/SertRoot/
      dest: /home/user/SertRoot/
      owner: user
      group: users
      mode: 0644
      force: yes
      
- hosts: all
  gather_facts: no      
  tasks:
    - command: sh /home/user/SertRoot/CAtoCert9.sh
      
- hosts: all
  gather_facts: no      
  tasks:
  - name: Del sert
    file:
        path: "/home/user/SertRoot/"
        state: absent
