- hosts: all
  gather_facts: no
  tasks:
  - name: Copy sert
    copy:
      src: file/Minkomsvaz020721.cer
      dest: /home/user/Minkomsvaz020721.cer 
      owner: user
      group: users
      mode: 0644
      force: yes
      
- hosts: all
  gather_facts: no      
  tasks:
    - shell: /opt/cprocsp/bin/amd64/certmgr -install /home/user/Minkomsvaz020721.cer
      
- hosts: all
  gather_facts: no      
  tasks:
  - name: Clean  shortcut firefox
    file:
        path: "/home/user/Minkomsvaz020721.cer"
        state: absent
