# apt-get update
# apt-get upgrade
# apt-get dist-upgrade
########################################
- hosts: all
  gather_facts: no
  tasks:
    - name: "Разблокировка SecretNet" 
      shell: |
      # Копируем fstab командой  "cp /etc/fstab /etc/fstab.backup"
        cp /etc/fstab /etc/fstab.backup
        /opt/secretnet/bin/snaidectl -i
        /opt/secretnet/sbin/snunblock
      register: secret_net_output
    - name: Вывод результатов SecretNet
      debug:
        var: secret_net_output.stdout_lines
        
    # Удаляем SecretNet через apt
    - name: "Удаление программы SecretNet"
      apt:
        name: secretnet
        state: absent

    - name: "Установка python-apt"
      shell: |
      # Меняем обратно fstab командой  "cp /etc/fstab.backup /etc/fstab"
        cp /etc/fstab.backup /etc/fstab
        apt update -y
        apt install python-apt -y
      register: python_apt_output
    - name: Вывод результатов установки python-apt
      debug:
        var: python_apt_output.stdout_lines

    - name: Выполнение команды <apt-get update>
      apt:
        update_cache: yes
        force_apt_get: yes
      register: apt_update_output
    - name: Вывод результатов apt-get update
      debug:
        var: apt_update_output.stdout_lines

    - name: Выполнение команды <apt-get upgrade>
      apt:
        upgrade: dist
        force_apt_get: yes
      register: apt_upgrade_output
    - name: Вывод результатов apt-get upgrade
      debug:
        var: apt_upgrade_output.stdout_lines
        
    - name: "Reboot системы"
      shell: |
        reboot
      register: reboot
    - name: Вывод результатов Reboot системы
      debug:
        var: reboot.stdout_lines
        
        #############################
    - name: Ожидание доступности системы
      wait_for_connection:
        delay: 30
        timeout: 300
      become: false

    - name: Вывод сообщения после перезагрузки
      debug:
        msg: "Система ребутнулась и подключилась для дальнейшей работы"

