# apt-get update
# apt-get upgrade
# apt-get dist-upgrade
########################################
- hosts: all
  gather_facts: no
  tasks:
    - name: "Разблокировка SecretNet" 
      shell: |
         cp /etc/fstab /etc/fstab.backup
         /opt/secretnet/bin/snaidectl -i
         /opt/secretnet/sbin/snunblock
      register: secret_net_output
    - name: Вывод результатов SecretNet
      debug:
        var: secret_net_output.stdout_lines
        
    - name: "Установка python-apt"
      apt:
         name: python-apt
         state: present
      register: python_apt_output
    - name: Вывод результатов установки python-apt
      debug:
        var: python_apt_output.stdout_lines
        
    # Удаляем SecretNet через apt
    - name: "Удаление программы SecretNet"
      apt:
        name: secretnet
        state: absent

    - name: "Возвращаем backup после удаления SecretNet"
      shell: |
         cp /etc/fstab.backup /etc/fstab

    - name: "Выполнение команды <apt-get update>"
      apt:
        update_cache: yes
        force_apt_get: yes
      register: apt_update_output
    - name: Вывод результатов apt-get update
      debug:
        var: apt_update_output.stdout_lines

    - name: "Выполнение команды <apt-get upgrade>"
      apt: upgrade=dist force_apt_get=yes
      #register: apt_upgrade_output
    #- name: Вывод результатов apt-get upgrade
      #debug:
        #var: apt_upgrade_output.stdout_lines
        
    - name: "Reboot пк"
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
      
    - name: "Происходит перезапуск системы, осталось немного"
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
      become: false
      delegate_to: localhost
