#  sudo apt-get update
#  sudo apt-get upgrade
#  sudo apt-get dist-upgrade


#############################################
- hosts: all
  gather_facts: no
  tasks:
    - name: "Разблокировка и Удаление SecretNet"
      shell: |
        /opt/secretnet/bin/snaidectl -i
        /opt/secretnet/sbin/snunblock
        apt purge secretnet -y
        cat /proc/cpuinfo | grep "model name"

    - name: Выполнение команды <apt-get update>
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Выполнение команды <apt-get upgrade>
      apt:
        upgrade: dist
        force_apt_get: yes
