# Разблокировка SecretNet
# Удаление SecretNet  ->  apt purge secretnet -y
# Начало обновления Linux  ->  "apt update -y"
# Начало обновления Linux  ->  "apt full-upgrade -y"
#- hosts: all
#  gather_facts: no
#  #команды
#  tasks:
#    - shell: hostname; /opt/secretnet/bin/snaidectl -i; /opt/secretnet/sbin/snunblock; apt purge secretnet -y; apt update -y; apt full-upgrade -y; cat /proc/cpuinfo|grep "model name"
#      register: hostname
#
#    # Print the shell task's stdout.
#    - debug: msg={{ hostname.stdout }}
    
    
    
#############################################
#Если вопрос разный
- hosts: all
  gather_facts: no
  tasks:
    - shell: hostname; apt update -y; apt full-upgrade -y; cat /proc/cpuinfo | grep "model name"
      register: hostname
      ignore_errors: true
    - expect:
      command: sudo do-release-upgrade
      responses:
        "Enter your response:": "y"
        "Enter another response:": "n"
        "Хотите продолжить? [Д/н]:": "Y"
        when: hostname.failed
