# Разблокировка SecretNet
# Удаление SecretNet  ->  apt purge secretnet -y
# Начало обновления Linux  ->  "apt update"
# Начало обновления Linux  ->  "apt full-upgrade"
- hosts: all
  gather_facts: no
  #команды
  tasks:
    - shell: hostname; /opt/secretnet/bin/snaidectl -i; /opt/secretnet/sbin/snunblock; apt purge secretnet -y; apt update -y; apt full-upgrade -y; cat /proc/cpuinfo|grep "model name"
      register: hostname

    # Print the shell task's stdout.
    - debug: msg={{ hostname.stdout }}
