# Разблокировка SecretNet
# Удаление SecretNet  ->  apt purge secretnet -y
# Начало обновления Linux  ->  "apt update -y"
# Начало обновления Linux  ->  "apt full-upgrade -y"
#- hosts: all
#  gather_facts: no
#  #команды
#  tasks:
#    - shell: hostname; /opt/secretnet/bin/snaidectl -i; /opt/secretnet/sbin/snunblock; apt purge secretnet -y; apt update -y; apt full-upgrade -y; cat /proc/cpuinfo|grep "model name"
#      register: hostname
#
#    # Print the shell task's stdout.
#    - debug: msg={{ hostname.stdout }}
    
    
    
#############################################
#с ответом на вопрос
- hosts: all
  gather_facts: no
  tasks:
    - name: Обновление операционной системы
      shell: hostname; apt update -y; apt full-upgrade; cat /proc/cpuinfo | grep "model name"
      register: hostname
      ignore_errors: true

    - name: Выполнить обновление
      expect:
        command: sudo do-release-upgrade
        responses:
          "Enter your response:": "y"
          "Enter another response:": "n"
          "Хотите продолжить? [Д/н]:": "Y"
      when: hostname.failed
