########################################
# SOURCES1.LIST -> SOURCES LIST
# после обновления на 10ую версию линукса сделать:
# SOURCES2.LIST -> SOURCES LIST
########################################
# ДЛЯ ОБНОВЛЕНИЯ LINUX
# apt-get update
# apt-get upgrade
# apt-get dist-upgrade
########################################
# ДЛЯ ОБНОВЛЕНИЯ ЯДРА
#######(не то) apt update
#######(не то) sudo apt install build-essential libssl-dev libncurses-dev bison flex -y (ПОЯВЛЯЕТСЯ КНОПКА И ВЫБОР ДИСКА ДЛЯ УСТАНОВКА GRUB)
#######(не то) wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.3.3.tar.xz
#######(не то) tar -xf linux-6.3.3.tar.xz
#######(не то) cd linux-6.3.3
#######(не то) apt search linux-image (СМОРТИМ КАКИЕ ТЕПЕРЬ ЕСТЬ ЯДРА, ВЫБИРАЕМ И КОПИРУЕМ ЗЕЛЕНОЕ НАЗВАНИЕ ПОЛНОСТЬЮ, НАШЕ - linux-image-4.19.0-6-amd64 (которого нету по сути))
# apt-cache search linux-image (КАКИЕ ЯДРА МОЖНО ПОСТАВИТЬ)
# dpkg --list | grep linux-image (КАКИЕ ЯДРА УЖЕ СКАЧАНЫ)
# apt-get update
# apt-get install linux-image-4.19.0-6-amd64 -y (ЕСЛИ СТАВИТЬ НЕСКАЧАННОЕ ЯДРО, СЛЕТАЕТ SSHD_CONFIG -> СЛЕТАЕТ ПАРОЛЬ)
########################################
- hosts: all
  gather_facts: no
  tasks:
    - name: "Меняем sources.list на правильный из GitHub"  
      ignore_errors: yes
      become: yes
      copy:
        src: file/sources2.list
        dest: /etc/apt/sources.list
        force: yes
  
    - name: "Копия fstab" 
      shell: |
         cp /etc/fstab /etc/fstab.backup 
        
    - name: "Установка python-apt"
      apt:
        name: python-apt
        state: present
      become: true
      become_user: root
      ignore_errors: yes
        
    # Удаляем SecretNet через apt
    - name: "Удаление программы SecretNet"
      apt:
        name: secretnet
        state: absent
        
    - name: "Возвращаем fstab из backup после удаления SecretNet"
      shell: |
         cp /etc/fstab.backup /etc/fstab

    - name: "Выполнение команды 1. <apt update>"
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: "Выполнение команды 2. <apt upgrade>"
      apt:
        upgrade: yes
        force_apt_get: yes
      ignore_errors: yes
        
    - name: "Выполнение команды 3. <apt dist-upgrade>"
      apt:
        upgrade: dist
        force_apt_get: yes
      ignore_errors: yes
        
# ОБНОВЛЕНИЕ ЯДРА!
    - name: "Выполнение команды 1. <apt update>"
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: "Установка ядра linux-image-4.19.0-6-amd64"
      apt:
        name: linux-image-4.19.0-6-amd64
        state: present
        update_cache: yes
        force_apt_get: yes
      ignore_errors: yes
      become: true
      become_user: root

# НЕОБХОДИМО ПОСТАВИТЬ НУЖНУЮ ВЕРСИЮ SECRET NET
    - name: "Скачивание архива с удаленного доступа"
      shell: |
         cd /opt
         wget --user={{ usr }} --password={{ passw }} ftp://192.168.100.22/SN_LSP.tar 
    - name: "Разархивация SN_LSP.tar"
      unarchive:
         remote_src: true  # Искать файл на удаленном узле
         src: /opt/SN_LSP.tar  # Путь к файлу архива
         dest: /opt/  # Путь к каталогу, куда нужно разархивировать       
    - name: "Удаление файла SN_LSP.tar"
      file:
        path: /opt/SN_LSP.tar
        state: absent
    - name: "Разархивация"
      shell: |
         cd /opt/SN_LSP/
         tar -xf debian10.1.tar.gz     
    - name: "Выполнение файла edit_repo.py"
      shell: |
         python3 edit_repo.py /opt/SN_LSP/repo
         truncate -s 0 /etc/apt/sources.list
    
    - name: "Меняем значение sources.list"
      shell: |
         echo "deb [trusted=yes] file:///opt/SN_LSP/repo ./" | sudo tee -a /etc/apt/sources.list
         apt update  
         
    - name: "Установка SecretNeta"
      apt:
         deb: "/opt/SN_LSP/sn-lsp_1.10-660.debian10.1_amd64.deb"
         state: present
      
  
    - name: "Reboot пк"
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
      
    - name: "Происходит перезапуск системы, осталось немного"
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
      become: false
      delegate_to: localhost
