- hosts: all
  gather_facts: no
  tasks:
    - name: "Разблокировка и Удаление SecretNet"
      shell: |
        /opt/secretnet/bin/snaidectl -i
        /opt/secretnet/sbin/snunblock
        apt purge secretnet -y
        cat /proc/cpuinfo | grep "model name"
      register: secret_net_output

    - name: Вывод результатов SecretNet
      debug:
        var: secret_net_output.stdout_lines

    - name: "Установка python-apt"
      shell: |
        sudo apt update -y
        sudo apt install python-apt -y
      register: python_apt_output

    - name: Вывод результатов установки python-apt
      debug:
        var: python_apt_output.stdout_lines

    - name: Выполнение команды <apt-get update>
      apt:
        update_cache: yes
        force_apt_get: yes
      register: apt_update_output

    - name: Вывод результатов apt-get update
      debug:
        var: apt_update_output.stdout_lines

    - name: Выполнение команды <apt-get upgrade>
      apt:
        upgrade: dist
        force_apt_get: yes
      register: apt_upgrade_output

    - name: Вывод результатов apt-get upgrade
      debug:
        var: apt_upgrade_output.stdout_lines
