########################################
# SOURCES1.LIST -> SOURCES LIST
# после обновления на 10ую версию линукса сделать:
# SOURCES2.LIST -> SOURCES LIST
########################################
# ДЛЯ ОБНОВЛЕНИЯ LINUX
# apt-get update
# apt-get upgrade
# apt-get dist-upgrade
########################################
# ДЛЯ ОБНОВЛЕНИЯ ЯДРА
#######(не то) apt update
#######(не то) sudo apt install build-essential libssl-dev libncurses-dev bison flex -y (ПОЯВЛЯЕТСЯ КНОПКА И ВЫБОР ДИСКА ДЛЯ УСТАНОВКА GRUB)
#######(не то) wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.3.3.tar.xz
#######(не то) tar -xf linux-6.3.3.tar.xz
#######(не то) cd linux-6.3.3
#######(не то) apt search linux-image (СМОРТИМ КАКИЕ ТЕПЕРЬ ЕСТЬ ЯДРА, ВЫБИРАЕМ И КОПИРУЕМ ЗЕЛЕНОЕ НАЗВАНИЕ ПОЛНОСТЬЮ, НАШЕ - linux-image-4.19.0-6-amd64 (которого нету по сути))
# apt-cache search linux-image (КАКИЕ ЯДРА МОЖНО ПОСТАВИТЬ)
# dpkg --list | grep linux-image (КАКИЕ ЯДРА УЖЕ СКАЧАНЫ)
# apt-get update
# apt-get install linux-image-4.19.0-6-amd64 (ЕСЛИ СТАВИТЬ НЕСКАЧАННОЕ ЯДРО, СЛЕТАЕТ SSHD_CONFIG -> СЛЕТАЕТ ПАРОЛЬ)
########################################
- hosts: all
  gather_facts: no
  tasks:
    - name: "Reboot пк"
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
      
    - name: "Происходит перезапуск системы, осталось немного"
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
      become: false
      delegate_to: localhost
  
    - name: "Копия fstab" 
      shell: |
         cp /etc/fstab /etc/fstab.backup 
# fstab.backup уже может существовать в системе
      register: secret_net_output
    - name: Вывод результата копии fstab и разблокировки SecretNet
      debug:
        var: secret_net_output.stdout_lines
        
    - name: Установка python-apt
      apt:
        name: python-apt
        state: present
      become: true
      become_user: root
      ignore_errors: yes
      register: python_apt_output
    - name: Вывод результатов установки python-apt
      debug:
        var: python_apt_output.stdout_lines
        
    # Удаляем SecretNet через apt
    - name: "Удаление программы SecretNet"
      apt:
        name: secretnet
        state: absent

    - name: "Выполнение команды <apt-get update>"
      apt:
        update_cache: yes
        force_apt_get: yes
      register: apt_update_output
    - name: Вывод результатов apt-get update
      debug:
        var: apt_update_output.stdout_lines

    - name: "Выполнение команды <apt-get upgrade>"
      apt: upgrade=dist force_apt_get=yes
      register: apt_upgrade_output
      ignore_errors: yes
    - name: "Вывод результатов <apt-get upgrade>"
      debug:
        var: apt_upgrade_output.stdout_lines
        
    - name: "Установка необходимых пакетов вместе с <apt update>"
      become: true
      apt:
        name:
          - build-essential
          - libssl-dev
          - libncurses-dev
          - bison
          - flex
        state: present
        update_cache: yes
        
        
        
        
    - name: "Возвращаем backup после удаления SecretNet"
      shell: |
         cp /etc/fstab.backup /etc/fstab
         
#    - name: "Reboot пк"
#      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
#      async: 1
#      poll: 0
#      
#    - name: "Происходит перезапуск системы, осталось немного"
#      local_action: wait_for host={{ inventory_hostname }} port=22 delay=20 connect_timeout=200
#      become: false
#      delegate_to: localhost
