- hosts: all
  tasks:
    - name: Out version vipnetclient
      command: dpkg-query -W vipnetclient 		#проверяем наличие установленного пакета vipnetclient, если пакета нет, останов, далее не выполняется
      register: my_package_check_deb			#записываем результат в переменную my_package_check_deb, если пакета нет, останов
    - name: out version vipnet"
      debug: 
        msg={{ my_package_check_deb.stdout }} 	# Выводим my_package_check_deb на экран	
     
    - name: Copy vipnetclient
      copy:
        src: file/vipnetclient_gost_ru_amd64_4.12.2-12236.deb
        dest: /home/user/vipnetclient_gost_ru_amd64_4.12.2-12236.deb
        owner: user
        group: users
        mode: 0644
        force: yes
      when: my_package_check_deb.stdout != "vipnetclient\t4.12.2-12236" #если выполняется, выполняем copy vipnetclient
      
    - name: Install vipnetclient                            #install vipnetclient
      apt: 
        deb="/home/user/vipnetclient_gost_ru_amd64_4.12.2-12236.deb"
      when: my_package_check_deb.stdout != "vipnetclient\t4.12.2-12236" #если выполняется, выполняем install vipnetclient
      
    - name: Delete packet vipnetclient.dpkg                 #удаляем vipnetclient
      file:
        path: "/home/user/vipnetclient_gost_ru_amd64_4.12.2-12236.deb"
        state: absent
      when: my_package_check_deb.stdout != "vipnetclient\t4.12.2-12236" #если выполняется, удаляем vipnetclient
      
    - name: change iplir.conf                                #меняем на mssdecrease= 200
      lineinfile: 
        dest: /root/.vipnet/data/user/iplir.conf
        regexp: '^mssdecrease= 0'  #строка, которую заменяем
        line: 'mssdecrease= 200' #строка, на которую заменяем
      when: my_package_check_deb.stdout != "vipnetclient\t4.12.2-12236" #если выполняется, меняем на mssdecrease= 200

    - name: restart vipnetclient                      #перезапуск vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient stop"
       - "vipnetclient start"
      when: my_package_check_deb.stdout != "vipnetclient\t4.12.2-12236" #перезапуск vipnetclient
