- hosts: all
  tasks:
    - name: change iplir.conf                                #меняем на mssdecrease= 200
      lineinfile: 
        dest: "/root/.vipnet/data/user/iplir.conf"
        regexp: '^(.*)mssdecrease= 0(.*)$'
        line: '\1mssdecrease= 200\2'
        backrefs: yes
        
    - name: restart vipnetclient                      #перезапуск vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient stop"
       - "vipnetclient start"
