- hosts: all
  tasks:
   - name: restart vipnetclient                      #перезапуск vipnetclient
     command: "{{ item }}"
     args:
     with_items:
      - "vipnetclient stop"
         
   - name: change iplir.conf                                #меняем на mssdecrease= 200
     lineinfile: 
        dest: /root/.vipnet/data/user/iplir.conf
        regexp: ^mssdecrease=
        line: mssdecrease= 200
                
   - name: restart vipnetclient                      #перезапуск vipnetclient
     command: "{{ item }}"
     args:
     with_items:
      - "vipnetclient start"
