- hosts: all
  tasks:
    - name: change iplir.conf                                #меняем на mssdecrease= 200
      lineinfile: 
        dest: /root/.vipnet/data/user/iplir.conf
        regexp: '^mssdecrease= 0'  #строка, которую заменяем
        line: 'mssdecrease= 200' #строка, на которую заменяем
        
    - name: restart vipnetclient                      #перезапуск vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient stop"
       - "vipnetclient start"
