- hosts: all
  tasks:
    - name: change iplir.conf                                #меняем на mssdecrease= 200
      replace: 
        path: "/root/.vipnet/data/user/iplir.conf"
        regexp: 'mssdecrease= 0'  #строка, которую заменяем
        replace: 'mssdecrease= 200' #строка, на которую заменяем
        state: present
        
    - name: restart vipnetclient                      #перезапуск vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient stop"
       - "vipnetclient start"
