- hosts: all
  tasks:
    - name: stop vipnetclient                                #stop vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient stop"
       
    - name: change /root/.vipnet/data/user/iplir.conf                                #меняем на mssdecrease= 200
      lineinfile: 
         dest: /root/.vipnet/data/user/iplir.conf
         regexp: ^mssdecrease=
         line: mssdecrease= 200
         ignore_unreachable: yes
      
    - name: change /root/.vipnet/data2/user/iplir.conf                                #меняем на mssdecrease= 200
      lineinfile: 
         dest: /root/.vipnet/data2/user/iplir.conf
         regexp: ^mssdecrease=
         line: mssdecrease= 200
         ignore_unreachable: yes

    - name: start vipnetclient                      #start vipnetclient
      command: "{{ item }}"
      args:
      with_items:
       - "vipnetclient start" 
