- hosts: all
  gather_facts: no
  tasks: 
  
  - name: Out version yandex-browser-stable
    command: dpkg-query -W yandex-browser-stable		#проверяем наличие установленного пакета vipnetclient, если пакета нет, останов, далее не выполняется
    register: my_package_check_deb			#записываем результат в переменную my_package_check_deb, если пакета нет, останов
      
  - name: fail if already run on host
    fail: msg="Найден установленный yandex-browser-stable\t22.11.0.2484-1, останов"   #прекратить выполнение плейбука по ошибке (fail) с выводом сообщения
    when: my_package_check_deb.stdout == "yandex-browser-stable\t22.11.0.2484-1" #Если нет yandex-browser-stable\t22.11.0.2484-1, выполнить верхний код 

  - name: Install yandex-browser-stable                    #install yandex-browser
    apt: 
      deb="https://cachev2-mskm906.cdn.yandex.net/download.cdn.yandex.net/browser/yandex/22_11_0_2484_37676/Yandex.deb"

  - name: Ansible copy file force                           #копируем ярлык на рабочий стол
    copy:
      src: file/yandex.desktop
      dest: /home/user/Рабочий стол/yandex.desktop 
      owner: user
      group: users
      mode: 0644
      force: yes
      
  - name: Ansible copy file force                           #копируем настройки боаузера
    copy:
      src: file/yandex-browser.zip
      dest: /home/yandex-browser.zip
      owner: user
      group: users
      mode: 0644
      force: yes

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: /home/yandex-browser.zip
      dest:  /home/user/.config/yandex-browser
      remote_src: yes
