- hosts: all
  gather_facts: yes

  tasks:  
    - name: "Check if yandex-browser-stable/now 22.11.0.2484-1 is installed"
      package_facts:
        manager: "auto"

    - name: "NGINX test result"
      debug: 
        msg: "NGINX found"
      when: "'yandex-browser-stable/now 22.11.0.2484-1' in ansible_facts.packages"

    - name: "NGINX test result"
      debug: 
        msg: "yandex-browser-stable/now 22.11.0.2484-1 NOT found"
      when: "'nginx' not in ansible_facts.packages"
