- hosts: all
  gather_facts: no
  tasks: 
  - name: Install yandex-browser-stable                    #install yandex-browser
    apt: 
      deb="https://cachev2-mskm906.cdn.yandex.net/download.cdn.yandex.net/browser/yandex/22_11_0_2484_37676/Yandex.deb"
