- hosts: all
  gather_facts: no
  tasks: 
  
  - name: Out version yandex-browser-stable
    ignore_errors: yes
    command: dpkg-query -W yandex-browser-stable		#запро версии yandex-browser-stable
    register: my_package_check_deb			#записываем результат в переменную my_package_check_deb
      
  - name: fail if already run on host
    fail: msg="Найден установленный yandex-browser-stable\t22.11.0.2484-1, останов"   #прекратить выполнение плейбука по ошибке (fail) с выводом сообщения
    when: my_package_check_deb.stdout == "yandex-browser-stable\t22.11.0.2484-1" #Если нет yandex-browser-stable\t22.11.0.2484-1, выполнить верхний код 

  - name: Install yandex-browser-stable                    #install yandex-browser
    apt: 
      deb="https://cachev2-mskm906.cdn.yandex.net/download.cdn.yandex.net/browser/yandex/22_11_0_2484_37676/Yandex.deb"

  - name: Ansible copy file yandex-browser.desktop                          #копируем ярлык на рабочий стол
    copy:
      src: file/yandex.desktop
      dest: /home/user/Рабочий стол/yandex.desktop 
      owner: user
      group: users
      mode: 0644
      force: yes
      
  - name: Ansible copy file yandex-browser.zip                         #копируем настройки боаузера
    copy:
      src: file/yandex-browser.zip
      dest: /home/yandex-browser.zip
      owner: user
      group: users
      mode: 0644
      force: yes

  - name: сreate directory
    file:
      path: /home/user/.config/yandex-browser
      mode: 0744
      owner: user
      group: users
      state: directory      

  - name: Unarchive a file
    unarchive:
      src: /home/yandex-browser.zip
      dest:  /home/user/.config/yandex-browser
      remote_src: yes
      mode: 0744
      owner: user
      group: users
