- hosts: all
  gather_facts: yes

  tasks:  
    - name: "Check if yandex-browser-stable/now 22.11.0.2484-1 is installed"
      package_facts:
        manager: "auto"

    - name: "yandex-browser-stable test result"
      debug: 
        msg="yandex-browser-stable Установлен"              #если установленн, прерываем выполнение
      when: "'andex-browser-stable' in ansible_facts.packages"

    - name: "yandex-browser-stable test result"
      debug: 
        msg: "yandex-browser-stable не установлен"
      when: "'andex-browser-stable' not in ansible_facts.packages"
