- hosts: all
  gather_facts: yes

  tasks:  
    - name: "Check if yandex-browser-stable/now 22.11.0.2484-1 is installed"
      package_facts:
        manager: "auto"

    - name: "yandex-browser-stable/now 22.11.0.2484-1 test result"
      debug: 
        fail: msg="yandex-browser-stable/now 22.11.0.2484-1 Установлен"              #если установленн, прерываем выполнение
      when: "'yandex-browser-stable' in ansible_facts.packages"

    - name: "yandex-browser-stable/now 22.11.0.2484-1 test result"
      debug: 
        msg: "yandex-browser-stable/now 22.11.0.2484-1 не установлен"
      when: "'nginx' not in ansible_facts.packages"
