- hosts: all
  gather_facts: no
  tasks: 
  
  - name: Out version yandex-browser-stable
    command: dpkg-query -W yandex-browser-stable		#проверяем наличие установленного пакета vipnetclient, если пакета нет, останов, далее не выполняется
    register: my_package_check_deb			#записываем результат в переменную my_package_check_deb, если пакета нет, останов
      
  - name: fail if already run on host
    fail: msg="Найден установленный yandex-browser-stable\t22.11.0.2484-1, останов"   #прекратить выполнение плейбука по ошибке (fail) с выводом сообщения
    when: my_package_check_deb.stdout = "yandex-browser-stable\t22.11.0.2484-1" #Если нет yandex-browser-stable\t22.11.0.2484-1, выполнить верхний код 
    
